.TH "MathematicalFunctions.h" 3 "Tue Jul 6 2021" "Version v1.0" "k-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MathematicalFunctions.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Point\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmf\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBmf::minSize\fP (\fBPoint\fP &p, \fBPoint\fP &q)"
.br
.ti -1c
.RI "double \fBmf::mean\fP (\fBPoint\fP &p)"
.br
.ti -1c
.RI "double \fBmf::stDev\fP (\fBPoint\fP &p)"
.br
.ti -1c
.RI "double \fBmf::euclideanDistance\fP (\fBPoint\fP &p, \fBPoint\fP &q)"
.br
.ti -1c
.RI "double \fBmf::euclideanDistanceSquared\fP (\fBPoint\fP &p, \fBPoint\fP &q)"
.br
.ti -1c
.RI "double \fBmf::manhattanDistance\fP (\fBPoint\fP &p, \fBPoint\fP &q)"
.br
.ti -1c
.RI "double \fBmf::chebyshevDistance\fP (\fBPoint\fP &p, \fBPoint\fP &q)"
.br
.ti -1c
.RI "double \fBmf::brayCurtisDistance\fP (\fBPoint\fP &p, \fBPoint\fP &q)"
.br
.ti -1c
.RI "double \fBmf::canberraDistance\fP (\fBPoint\fP &p, \fBPoint\fP &q)"
.br
.ti -1c
.RI "double \fBmf::pearsonCorrelation\fP (\fBPoint\fP &p, \fBPoint\fP &q)"
.br
.ti -1c
.RI "double \fBmf::cosineSimilarity\fP (\fBPoint\fP &p, \fBPoint\fP &q)"
.br
.ti -1c
.RI "double \fBmf::dot\fP (\fBPoint\fP &p, \fBPoint\fP &q)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for k-means in native C++ from the source code\&.
