.TH "md__r_e_a_d_m_e" 3 "Tue Jul 6 2021" "Version v1.0" "k-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- README 
This repo contains the implementation of the k-means clustering machine learning algorithm:
.PP
https://en.wikipedia.org/wiki/K-means_clustering
.PP
as a native C++ application\&.
.PP
The documentation of the project is in the /doc directory\&. 
