.TH "PropertiesParser.cpp" 3 "Tue Jul 6 2021" "Version 1.0" "k-means in native C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PropertiesParser.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'PropertiesParser\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for k-means in native C++ from the source code\&.
